<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="5" total="12" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Suite1" duration-ms="66" started-at="2025-03-23T12:12:04Z" finished-at="2025-03-23T12:12:05Z">
    <groups>
      <group name="MyTest">
        <method signature="TestvinExam1.test2()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test2" class="vinTestngStart.TestvinExam1"/>
        <method signature="TestvinExam1.test3()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test3" class="vinTestngStart.TestvinExam1"/>
        <method signature="TestvinExam1.test6()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test6" class="vinTestngStart.TestvinExam1"/>
        <method signature="TestvinExam2.test7()[pri:2, instance:vinTestngStart.TestvinExam2@145ad3d]" name="test7" class="vinTestngStart.TestvinExam2"/>
        <method signature="TestvinExam2.test9()[pri:1, instance:vinTestngStart.TestvinExam2@145ad3d]" name="test9" class="vinTestngStart.TestvinExam2"/>
      </group> <!-- MyTest -->
    </groups>
    <test name="forgnewchecjkvinGroupExample" duration-ms="66" started-at="2025-03-23T12:12:04Z" finished-at="2025-03-23T12:12:05Z">
      <class name="vinTestngStart.TestvinExam1">
        <test-method status="PASS" signature="test2()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test2" duration-ms="11" started-at="2025-03-23T17:42:04Z" finished-at="2025-03-23T17:42:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test3" duration-ms="3" started-at="2025-03-23T17:42:04Z" finished-at="2025-03-23T17:42:04Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at vinTestngStart.TestvinExam1.test3(TestvinExam1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="SKIP" signature="test3()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test3" duration-ms="2" started-at="2025-03-23T17:42:05Z" finished-at="2025-03-23T17:42:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at vinTestngStart.TestvinExam1.test3(TestvinExam1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="FAIL" signature="test3()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test3" duration-ms="2" started-at="2025-03-23T17:42:05Z" finished-at="2025-03-23T17:42:05Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at vinTestngStart.TestvinExam1.test3(TestvinExam1.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:998)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1200)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test3 -->
        <test-method status="PASS" signature="test6()[pri:0, instance:vinTestngStart.TestvinExam1@104ce99]" name="test6" duration-ms="2" started-at="2025-03-23T17:42:05Z" finished-at="2025-03-23T17:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test6 -->
      </class> <!-- vinTestngStart.TestvinExam1 -->
      <class name="vinTestngStart.TestvinExam2">
        <test-method status="PASS" signature="test9()[pri:1, instance:vinTestngStart.TestvinExam2@145ad3d]" name="test9" duration-ms="2" started-at="2025-03-23T17:42:05Z" finished-at="2025-03-23T17:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test9 -->
        <test-method status="PASS" signature="test7()[pri:2, instance:vinTestngStart.TestvinExam2@145ad3d]" name="test7" duration-ms="2" started-at="2025-03-23T17:42:05Z" finished-at="2025-03-23T17:42:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test7 -->
      </class> <!-- vinTestngStart.TestvinExam2 -->
    </test> <!-- forgnewchecjkvinGroupExample -->
  </suite> <!-- Suite1 -->
</testng-results>
